Contiki 3.x: Link Layer Security Common Functionality
Link Layer Security Common Functionality
Communication stacks » Link Layer Security
Common functionality of 802.15.4-compliant llsec_drivers.
Data Structures
struct ccm_star_driver
Structure of CCM* drivers.
Functions
void anti_replay_set_counter (void)
Sets the frame counter packetbuf attributes.
uint32_t anti_replay_get_counter (void)
Gets the frame counter from packetbuf.
void anti_replay_init_info (struct anti_replay_info *info)
Initializes the anti-replay information about the sender.
int anti_replay_was_replayed (struct anti_replay_info *info)
Checks if received frame was replayed.
Detailed Description
Common functionality of 802.15.4-compliant llsec_drivers.
Function Documentation
void anti_replay_init_info (struct anti_replay_info * info)
Initializes the anti-replay information about the sender.
Parameters
info Anti-replay information about the sender
Definition at line 76 of file anti-replay.c.
References anti_replay_get_counter().
int anti_replay_was_replayed (struct anti_replay_info * info)
Checks if received frame was replayed.
Parameters
info Anti-replay information about the sender
Return values
0 <-> received frame was not replayed
Definition at line 84 of file anti-replay.c.
References anti_replay_get_counter(), and packetbuf_holds_broadcast().