Contiki 3.x: cc2538 Clock
cc2538 Clock
Contiki platforms » TI cc2538-powered platforms » The TI cc2538 System-on-Chip
Implementation of the clock module for the cc2538.
Files
file clock.c
Clock driver implementation for the TI cc2538.
Functions
void clock_init (void)
Arch-specific implementation of clock_init for the cc2538.
CCIF clock_time_t clock_time (void)
Get the current clock time.
void clock_set_seconds (unsigned long sec)
Set the value of the platform seconds.
CCIF unsigned long clock_seconds (void)
Get the current value of the platform seconds.
void clock_wait (clock_time_t i)
Wait for a given number of ticks.
void clock_delay_usec (uint16_t dt)
Delay a given number of microseconds.
void clock_delay (unsigned int i)
Obsolete delay function but we implement it here since some code still uses it.
void clock_adjust (void)
Adjust the clock following missed SysTick ISRs.
void clock_isr (void)
The clock Interrupt Service Routine.
Detailed Description
Implementation of the clock module for the cc2538.
To implement the clock functionality, we use the SysTick peripheral on the cortex-M3. We run the system clock at a configurable speed and set the SysTick to give us 128 interrupts / sec. However, the Sleep Timer counter value is used for the number of elapsed ticks in order to avoid a significant time drift caused by PM1/2. Contrary to the Sleep Timer, the SysTick peripheral is indeed frozen during PM1/2, so adjusting upon wake-up a tick counter based on this peripheral would hardly be accurate.
Function Documentation
void clock_adjust (void)
Adjust the clock following missed SysTick ISRs.
This function is useful when coming out of PM1/2, during which the system clock is stopped. We adjust the clock counters like after any SysTick ISR.
Note
This function is only meant to be used by lpm_exit(). Applications should really avoid calling this
Definition at line 230 of file clock.c.
void clock_delay_usec (uint16_t dt)
Delay a given number of microseconds.
Parameters
dt How many microseconds to delay.
Note
Interrupts could increase the delay by a variable amount.
< GPTIMER0
< GPTM Timer A interval load
< GPTIMER0
< GPTM control
< Timer A enable
< GPTIMER0
< GPTM control
< Timer A enable
Definition at line 156 of file clock.c.
References GPT_0_BASE, GPTIMER_CTL, GPTIMER_CTL_TAEN, and GPTIMER_TAILR.
Referenced by clock_delay(), i2c_init(), i2c_master_command(), and main().
void clock_init (void)
Arch-specific implementation of clock_init for the cc2538.
Initialize the clock library.
We initialise the SysTick to fire 128 interrupts per second, giving us a value of 128 for CLOCK_SECOND
We also initialise GPT0:Timer A, which is used by clock_delay_usec(). We use 16-bit range (individual), count-down, one-shot, no interrupts. The prescaler is computed according to the system clock in order to get 1 tick per usec.
< GPT[3:0] clocks - active mode
< GPT0 clock enable, CPU running
< GPTIMER0
< GPTM control
< GPTIMER0
< GPTM configuration
< GPTIMER0
< GPTM Timer A mode
< GPTIMER0
< GPTM Timer A prescale
Definition at line 93 of file clock.c.
References GPT_0_BASE, GPTIMER_CFG, GPTIMER_CTL, GPTIMER_TAMR, GPTIMER_TAPR, SYS_CTRL_RCGCGPT, and SYS_CTRL_RCGCGPT_GPT0.
void clock_isr (void)
The clock Interrupt Service Routine.
It polls the etimer process if an etimer has expired. It also updates the software clock tick and seconds counter.
Definition at line 248 of file clock.c.
CCIF unsigned long clock_seconds (void)
Get the current value of the platform seconds.
This could be the number of seconds since startup, or since a standard epoch.
Returns
The value.
Definition at line 136 of file clock.c.
void clock_set_seconds (unsigned long sec)
Set the value of the platform seconds.
Parameters
sec The value to set.
Definition at line 130 of file clock.c.
CCIF clock_time_t clock_time (void)
Get the current clock time.
This function returns the current system clock time.
Returns
The current clock time, measured in system ticks.
Definition at line 124 of file clock.c.
Referenced by clock_wait().
void clock_wait (clock_time_t t)
Wait for a given number of ticks.
Parameters
t How many ticks.
Definition at line 142 of file clock.c.
References clock_time().